#ifndef _ERROR_H
#define _ERROR_H
#define NOT_VALID_VARIABLE 49
#define NOT_VALID_VARIABLE_TYPE 50
#define NOT_VALID_INTEGER_TYPE 52
#define INVALID_IDENTIFIER 53
#define INVALID_INTEGER 54
#define TRUE 4
#define FALSE 3
#define NOCODE 55
#define ERROR_CODE 56
#define NOT_ALPHA 57
#define ERROR_COMMAND 58
#define ERROR_VARIABLE 59
#define ERROR_DUPLICATE_VARIABLE 60
#define ERROR_VALUE 61
#define VARIABLE_DOES_NOT_EXIST 62
#define CONFIG_NXT_GCODE 63
int CMD_RETRIEVED;

#endif // _ERROR_H
